### ISSUE TITLE
Crossbow def name has gun instead of bow, causing error spam

### ISSUE THREAD

**Issue by blazeb75** [onigamii/VanillaWeaponsExpandedCE#2]
On line 50 of the xml for the crossbow, the def name 'VWE_Gun_Crossbow' needs to be replaced with 'VWE_Bow_Crossbow'. Currently, there's console spam whenever you press i on a crossbow or load a save with a crossbow in it (even on world pawns, I think).

**Comment by onigamii** [comment]
Fixed now, thanks!
